### PR TITLE
Tabs dropdown

### PR DESCRIPTION
**Pull request by jefrog1844**
Done - tabs, dropdown (also refactored button to have a ripple directive and modified ripple style)

### CODE REVIEW

**Comment by amorey** [comment]
This PR was trying to overwrite files already changed in the master so I merged it manually. I think the problem is that that commit history might have gotten confused when you pulled from the master previously. Next time we should do a `git rebase` so the merge gets applied to the original branch point rather than on top of the current commit.

**Comment by jefrog1844** [comment]
Probably my fault. For the last updates I did the following:
1. fetch upstream (muicss/mui-angular)
2. merge upstream/master (applies changes to jefrog1844/mui-angular)
3. created branch tabs-dropdown
4. made several commits and pushed to origin
(jefrog/mui-angular/tabs-dropdown)
5. squash commits (git rebase -i master)
6. push --force origin???

So maybe I squashed to the wrong place in history?

Jeff

**Comment by amorey** [comment]
Based on these steps, I'm not sure where the problem could have come from. I wouldn't have expected the squash+force to confuse the pull request if `muicss/mui-angular/master` was at the same commit as your local master when you branched at Step 3. If you still have the git log for the tabs-dropdown branch we can look at it to see if/when the commit timelines diverged.

**Comment by jefrog1844** [comment]
MacBook-Air:mui-angular jeffrogers$ git log
commit c578f160792175fc15555ce8bb7c0d3d2b292df7 (HEAD -> tabs-dropdown,
origin/tabs-dropdown)
Author: Andres Morey <andresmarcel@gmail.com>
Date:   Fri Sep 18 13:22:40 2020 +0300

    - add dropdown, tabs, caret, ripple directive
    - refactor button, fix ripple code
    - fix button-page for disabled buttons

commit 109ec503966e0ab9315cef0ee3b9b783cb11b320 (mui-select)
Merge: 1a562c6 b3ee304
Author: Andres Morey <andresmarcel@gmail.com>
Date:   Thu Sep 17 23:08:33 2020 +0300

    Merge pull request #3 from jefrog1844/container

    add container, col, row, panel, divider, update appbar

commit b3ee3045db433f4dd9e5a04a07d6c5eee4d1a1f1
Author: Jeff Rogers <jefrog1844@gmail.com>
Date:   Sat Sep 12 23:03:41 2020 -0500

    add container, col, row, panel, divider, update appbar

commit 1a562c6f5adb9990f5d9486849ac87087ced7f88
Merge: 846116b d6b6a66
Author: Andres Morey <andresmarcel@gmail.com>
Date:   Mon Sep 14 10:24:31 2020 +0300

    Merge pull request #2 from jefrog1844/button

    add ripple, disabled.  use renderer.

commit d6b6a66b9992dcccf4270cc1ceb9fce3672ee707
Author: Jeff Rogers <jefrog1844@gmail.com>
Date:   Tue Sep 8 22:25:26 2020 -0500

    add ripple, disabled, use renderer, optional operators, add test case,
modify linting rules

commit 846116ba3e70c967aa63b92ccef52309524b6797
Author: Andres Morey <andresmarcel@gmail.com>
Date:   Tue Sep 8 23:14:53 2020 +0300

    added appbar and button components as secondary entrypoints, configured
example-app to include css for components

**Comment by amorey** [comment]
Looking at the commit log for muicss/mui-angular/master it looks like the commit history diverged after I merged your previous pull request (109ec503966e0ab9315cef0ee3b9b783cb11b320):

> commit 6ce05237903abf14b3a6a63009493ba2979bbb1f (HEAD -> master, origin/master, jefrog/master, jefrog_master)
> Author: Andres Morey <andresmarcel@gmail.com>
> Date:   Tue Sep 22 09:46:54 2020 +0300
>
>    added tabs and dropdowns, bugfix to button ripple position (@jefrog1844)
>
> commit e714359c06422a81f52c7298c2872da5c979e2a7
> Author: Andres Morey <andresmarcel@gmail.com>
> Date:   Fri Sep 18 13:41:22 2020 +0300
> 
>    added button and grid examples, added panel-page and renamed home to home-page in example-app
>
> commit 3606dd4c393912741aaec9621c07bdee53124c12
> Author: Andres Morey <andresmarcel@gmail.com>
> Date:   Fri Sep 18 13:22:40 2020 +0300
>
>    split components in example-app into separate pages
>
> commit 109ec503966e0ab9315cef0ee3b9b783cb11b320
> Merge: 1a562c6 b3ee304
> Author: Andres Morey <andresmarcel@gmail.com>
> Date:   Thu Sep 17 23:08:33 2020 +0300
>
>    Merge pull request #3 from jefrog1844/container
>    
>    add container, col, row, panel, divider, update appbar

So it appears the source of the problem is that somehow commit 3606dd4c393912741aaec9621c07bdee53124c12 got squashed in jefrog1844/mui-angular/tabs-dropdown. Is it possible that you created the branch from 109ec503966e0ab9315cef0ee3b9b783cb11b320 rather than 3606dd4c393912741aaec9621c07bdee53124c12? I think that would have allowed you to squash the commit when you did a git rebase later.

**Comment by jefrog1844** [comment]
I think you found it.  I believe I had already created the branch from
109ec50 and subsequently updated my master and merged 3606dd4 into my
master and branch, or at least thought I had.

For future reference, once I have created a branch, what is the proper
method to apply those changes to my forked repository and branch?

Thanks

Jeff

**Comment by amorey** [comment]
Cool, at least we figured it out. The proper way to merge changes from the original branch back into your current branch is to do a "git rebase". That will apply the changes to the original branch point rather than on top of the latest commit. This applies to forked repositories as well as feature branches:

```bash
# update local master from upstream master
$ git fetch upstream
$ git checkout master
$ git rebase -i upstream/master

# update feature branch from local branch
$ git checkout feature-branch
$ git rebase -i master
```

One thing to keep in mind is that "git rebase" allows you to squash commits in your current branch but the primary use case is for applying changes from the orginal branch. For squashing commits you can use "git merge --squash" when you merge your feature branch back into the main branch.

**Pull request closed without merging**
