### PR TITLE
add container, col, row, panel, divider, update appbar

### PR DESCRIPTION
**Pull request by jefrog1844**
Passed all lint and tests.  I had already incorporated vertical divider, but if you think it is not easy to follow I'll just implement the horizontal divider which won't take long :-)

### CODE REVIEW

**Comment by amorey** [comment]
Looks great! Thanks for the PR.

**Comment by jefrog1844** [comment]
Thanks.  What would you like next?

Jeff

**Comment by amorey** [comment]
How about tabs and dropdowns next and then we leave forms and form components for last?

Also, I split out the components in the example-app into separate pages so you should pull from the origin before branching.

**Comment by jefrog1844** [comment]
Sounds good and I'll go down that path.

Thanks

Jeff

**Pull request merged**
